# Generated by Django 2.0.4 on 2018-04-10 17:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='policy_type',
            fields=[
                ('policy_name', models.CharField(max_length=40)),
                ('policy_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_code',
        ),
        migrations.AddField(
            model_name='policy',
            name='policycode',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='customer.policy_type'),
            preserve_default=False,
        ),
    ]
