# Generated by Django 2.0.4 on 2018-04-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180410_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
                ('payment_num', models.AutoField(primary_key=True, serialize=False)),
                ('policyno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.policy')),
            ],
        ),
    ]
