# Generated by Django 2.0.4 on 2018-04-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
