# Generated by Django 2.0.4 on 2018-04-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180410_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('relationship', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='policy_holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('pol_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.policy')),
            ],
        ),
        migrations.CreateModel(
            name='policy_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.policy')),
                ('policy_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.payment')),
            ],
        ),
    ]
