# Generated by Django 2.0.4 on 2018-04-11 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_nominee_policy_holder_policy_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pass_word',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
