# Generated by Django 2.0.4 on 2018-04-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20180426_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy_type',
            name='policy_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
