# Generated by Django 2.0.3 on 2018-05-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20180426_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policy_payment',
            name='payment_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.payment'),
        ),
        migrations.AlterField(
            model_name='policy_payment',
            name='policy_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.policy'),
        ),
    ]
