# Generated by Django 2.0.4 on 2018-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('fname', models.CharField(max_length=80)),
                ('lname', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=120)),
                ('phone_no', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('agentid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
